# Generated by Django 6.0.5 on 2026-06-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('arabic', models.TextField()),
                ('translation', models.TextField()),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('travel', 'Travel'), ('prayer', 'Prayer'), ('food', 'Food'), ('sleep', 'Sleep'), ('anxiety', 'Anxiety'), ('rain', 'Rain')], max_length=50)),
            ],
        ),
    ]
