# Generated by Django 6.0.5 on 2026-06-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dua', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='reference',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
