# Generated by Django 6.0.5 on 2026-07-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surahnum', models.PositiveSmallIntegerField()),
                ('surahname', models.TextField(max_length=100)),
                ('ayahnum', models.PositiveSmallIntegerField()),
                ('arabic', models.TextField()),
                ('translate', models.TextField()),
                ('Reference', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='hadiths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('arabic', models.TextField()),
                ('translate', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=225, null=True)),
                ('category', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('prayer', 'Prayer'), ('sleep', 'Sleep'), ('wakeup', 'Wake Up'), ('food', 'Food & Drink'), ('travel', 'Travel'), ('anxiety', 'Anxiety & Stress'), ('sadness', 'Sadness'), ('forgiveness', 'Forgiveness'), ('protection', 'Protection'), ('gratitude', 'Gratitude'), ('patience', 'Patience'), ('guidance', 'Guidance'), ('knowledge', 'Knowledge'), ('parents', 'Parents'), ('marriage', 'Marriage'), ('family', 'Family'), ('children', 'Children'), ('work', 'Work & Study'), ('rizq', 'Rizq'), ('success', 'Success'), ('rain', 'Rain'), ('istikhara', 'Istikhara'), ('repentance', 'Repentance'), ('death', 'Death & Funeral'), ('general', 'General')], max_length=50)),
            ],
        ),
    ]
